### PR TITLE
add optional separator support to stringify

### PR DESCRIPTION
**Pull request by tetsuo**
``` js
stringify({foo:1,bar:2}, null, ';'); // foo=1;bar=2
```

### CODE REVIEW

**Comment by rlidwka** [comment]
I think that "null" really calls for an option object...

**Comment by tetsuo** [comment]
That's right. Changed stringify to accept an object now, keeping backwards compatibility:

``` js
stringify({foo:1,bar:2}, {separator: ';'}); // it is options if object is given
stringify({foo:1,bar:2}, 'foo'); // it is prefix if string is given
stringify({foo:1,bar:2}, {separator: ';', prefix: 'foo'}); // ...
```

**Comment by tj** [comment]
why not just use & like everyone else on the planet :D

**Comment by tetsuo** [comment]
heh, well semicolons is the new sexy. Resistance is futile.

**Comment by jonathanong** [comment]
kind of tempted to go full mongodb-retard with querystrings and `;`.

```
?a.b.c=1;key5.0=null;something=else;
```

and use something like https://github.com/hughsk/flat. heh

**Comment by rlidwka** [comment]
> heh, well semicolons is the new sexy

Yeah, I know quite a few people who have been saving semicolons in their js source code hoping to insert them into query strings instead. :P

**Comment by tetsuo** [comment]
actually it is quite possible that there are more people who use semicolons in query strings than people who use them correctly in sentences.

**Pull request closed without merging**
